project:
  type: website
  output-dir: docs
  resources:
    - assets/portfolio/index.yaml
    - assets/publications/index.yaml

website:
  title: "rkim.dev"
  page-navigation: true
  sidebar:
    style: floating
    search: false
    logo: ./assets/icons/profile.jpg
    border: false
    tools:
      - icon: linkedin
        menu:
          - text: kimryan0416
            href: https://www.linkedin.com/in/kimryan0416/
            target: _blank
      - icon: github
        menu:
          - text: Personal Github
            href: https://github.com/kimryan0416
            target: _blank
          - text: Tools
            href: https://github.com/SimpleDevs-Tools
            target: _blank
          - text: Research
            href: https://github.com/SimpleDevs-Research
            target: _blank
      - icon: envelope
        menu:
          - text: rkim.dev@proton.me
            href:  mailto:rkim.dev@proton.me
          - text: kim.ryan@nyu.edu
            href:  mailto:kim.ryan@nyu.edu
    contents:
      - href: index.qmd
        text: "<img src='/assets/icons/index.svg' class='nav_icon' /> Ryan Kim"
      
      - href: publications
        text: "<img src='/assets/icons/publication.svg' class='nav_icon' /> Publications"
      
      - href: portfolio
        text: "<img src='/assets/icons/portfolio.svg' class='nav_icon' /> Portfolio"
        contents:
          - text: Research
            href: portfolio/research/index.qmd
            contents: 
              - portfolio/research/screen_to_video_map/index.qmd
              - portfolio/research/looking_for_answers/index.qmd
              - portfolio/research/vr_rdw/index.qmd
              - portfolio/research/rvo_pathing/index.qmd
              - portfolio/research/bsph/index.qmd
              - portfolio/research/verisimilitude/index.qmd
              - portfolio/research/mol/index.qmd
              - portfolio/research/vrkeyboard/index.qmd
              - portfolio/research/livestreams/index.qmd
              - portfolio/research/service_search/index.qmd
          - text: Work Experience
            href: portfolio/work_experience/index.qmd
            contents:
              - portfolio/work_experience/ta_nyu_silva/index.qmd
              - portfolio/work_experience/ta_nyu_sun/index.qmd
              - portfolio/work_experience/mimo/index.qmd
              - portfolio/work_experience/umich_intern/index.qmd
              - portfolio/work_experience/tucan_fitness/index.qmd
              - portfolio/work_experience/oneplace/index.qmd
              - portfolio/work_experience/ecornell_autograder/index.qmd
              - portfolio/work_experience/ta_cornell/index.qmd
              - portfolio/work_experience/ichd/index.qmd
          - text: Projects
            href: portfolio/projects/index.qmd
            contents:
              - portfolio/projects/easiervrassets/index.qmd
              - portfolio/projects/patent_prediction/index.qmd
              - portfolio/projects/orbit/index.qmd
              - portfolio/projects/toste/index.qmd
              - portfolio/projects/smp/index.qmd
              - portfolio/projects/traveler/index.qmd
              - portfolio/projects/orientation/index.qmd
              - portfolio/projects/inky_escape/index.qmd
              - portfolio/projects/cyber_pursuit/index.qmd
              - portfolio/projects/bullet_space/index.qmd
              - portfolio/projects/horror_hospital/index.qmd
              - portfolio/projects/trihop/index.qmd
              - portfolio/projects/embarkment/index.qmd
              - portfolio/projects/pentatonic/index.qmd
          - text: VR Dev Guides
            href: https://rkimdev.notion.site/openxr-unity-development
            target: "_blank"
      
      - href: assets/resumes/resume-10.2025.pdf
        text: "<img src='/assets/icons/download.svg' class='nav_icon' /> Resume (111 Kb)"
        target: _blank
      
      - href: assets/resumes/cv-10.2025.pdf
        text: "<img src='/assets/icons/download.svg' class='nav_icon' /> CV (123 Kb)"
        target: _blank    

format:
  html:
    theme:
      - litera
      - cosmo
      - brand
    css: styles.css
    toc: false
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 0px
      gutter-width: 24px
    execute:
      python: .venv/bin/python # Or .venv/[Scripts/bin]/python.exe on Windows