---
title: "Cyber Pursuit"
subtitle: "A game designed for NYU Game Design 2024 - Week 4: Level Design."
format: 
    html:
        css: "../../style.css"
        anchor-sections: false
execute:
    echo: false
---

```{python}
# Imports
import yaml
from IPython.display import display, Markdown, HTML
from os import path

import sys
sys.path.append(path.abspath(path.join('..', '..', '..')))
import utils.helpers as h

project_yaml = path.join('..', 'items.yaml')
with open(project_yaml) as f:
    items = yaml.safe_load(f)
    details = [item for item in items if item['id']=='cyber_pursuit'][0]
    display(HTML(h.portfolio_item_details(details)))
```

::: {.panel-tabset}

## About

> Go through the city to find you stolen car! Beware of obstacles, including fires and people... 

A game designed for **NYU Game Design 2024 - Week 4: Level Design**.

### Teammates & Roles

- <u>Ryan Kim (me)</u> - Asset Organization, Scene Generation, HP system
- <u>Zhongyu Zhang</u> - Player Mechanics/Movement/Scene Interaction
- <u>Ian Alexander Mccullough</u> - Asset Collection, Audio Design, UI, Testing


## Details

### How to Play

1. Use W and D to move left and right on the screen.
2. Press Space to jump.
3. Press and hold S while moving to slide for a distance.
4. While in the air in front of a billboard, press and hold W to wall-run for a distance. You can jump off a billboard for extra distance in the air during a wall-run.
5. If you fall or lose too much health, you will restart at the closest checkpoint billboard.


:::
